name: google_place
description: "A new Flutter package for handling Google Place API: place search, details, photos, autocomplete, and query autocomplete requests."
version: 0.4.8
homepage: https://github.com/Rakibul25/google_place

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter